### ISSUE TITLE
Job fails Enqueue when passing Null for PerformContext

### ISSUE THREAD

**Issue by twurm** [face-it/Hangfire.Tags#1] opened 2019-02-07 21:32 UTC
## Background
We are seeing a null reference exception when calling Enqueue and passing Null for PerformContext.  Our Enqueue call looks like this:

```
BackgroundJob.Enqueue(() => ProcessFile(file.Name, fileContents, Config.CustomConfigurationEntries, /*PerformContext*/null));
```

```
2019-02-07 16:19:06.8422|ERROR|Background job creation failed. See inner exception for details.
Hangfire.BackgroundJobClientException: Background job creation failed. See inner exception for details. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Hangfire.Tags.States.CreateJobFilter.OnCreated(CreatedContext filterContext)
   at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
   at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
   at Hangfire.Client.BackgroundJobFactory.Create(CreateContext context)
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
   --- End of inner exception stack trace ---
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
   at FileProcessor.EnqueueFiles() 
```

## Version Information
Hangfire: 1.7 Beta 2
Hangfire.Tags: 0.6.0

**Comment by r-win** [comment] 2019-02-09 00:27
So, I've tried to reproduce this situation, but it seems to work for me.

        BackgroundJob.Enqueue(() => Job("Home", null, null));

        [Tag("job", "{0}", "{1}")]
        public void Job(string name, PerformContext ctx, IJobCancellationToken token)
        {
            TextBuffer.WriteLine("Background Job completed succesfully!");
        }

I've purposely added different tags to different arguments, but I'm not able to reproduce the exception. Can you append your Hangfire configuration?

**Comment by twurm** [comment] 2019-02-09 14:29
@r-win thanks for the quick reply.  I took another look, everything looks ok.  Below is my Hangfire config.

```csharp
services.AddHangfire(config =>
{
   config.UseSqlServerStorage(mxConnectionString, new SqlServerStorageOptions
   {
      SlidingInvisibilityTimeout = TimeSpan.FromMinutes(5), // To enable Sliding invisibility fetching
      CommandBatchMaxTimeout = TimeSpan.FromMinutes(5), // To enable command pipelining
         QueuePollInterval = TimeSpan.FromTicks(1) // To reduce processing delays to minimum
   });
         
   config.UseTagsWithSql();
   config.UseNLogLogProvider();
   config.UseHeartbeatPage(checkInterval: TimeSpan.FromSeconds(5));
});
```
I'm enqueueing the jobs like this:
```csharp
// configure recurring jobs
recurringJobs.AddOrUpdate("EventLog.Cleanup", Job.FromExpression<EventsController>(x => x.Cleanup()), Configuration["Maintenance:Events:CronExpression"], TimeZoneInfo.Local, webQueue);
```

Here is what the job method looks like:
```csharp
[Tag("Maintenance")]
public void Cleanup(PerformContext context)
{
   // Simple delete statement goes here
}
```

Below is the corresponding exception:
```
System.NullReferenceException: Object reference not set to an instance of an object. 
   at Hangfire.Tags.States.CreateJobFilter.OnCreated(CreatedContext filterContext) 
   at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation) 
   at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation) 
   at Hangfire.Client.BackgroundJobFactory.Create(CreateContext context) 
   at Hangfire.Server.RecurringJobScheduler.TryScheduleJob(JobStorage storage, IStorageConnection connection, String recurringJobId, IReadOnlyDictionary`2 recurringJob) 
   at Hangfire.Server.RecurringJobScheduler.<>c__DisplayClass9_0.b__0(IStorageConnection connection) 
   at Hangfire.Server.RecurringJobScheduler.UseConnectionDistributedLock(JobStorage storage, Action`1 action) 
   at Hangfire.Server.RecurringJobScheduler.Execute(BackgroundProcessContext context) 
   at Hangfire.Server.BackgroundProcessDispatcherBuilder.ExecuteProcess(Guid executionId, Object state) 
   at Hangfire.Processing.BackgroundExecution.Run(Action`2 callback, Object state)
```

**Comment by r-win** [comment] 2019-02-20 12:08
So, I've been trying to reproduce your issue again, but I really can't. But then I noticed something in your code, which may be a copy-paste error, but I just want to make sure.

Your method is defined like this:
`
[Tag("Maintenance")]
public void Cleanup(PerformContext context)
{
   // Simple delete statement goes here
}
`

but you're invoking it like this:
`x => x.Cleanup()`

I'm missing the argument to PerformContext here.

The CreateJobFilter method will try to locate the MethodInfo that's about to be invoked, in order to retrieve the Tag attribute(s). Is it possible that something is going wrong there?

**Comment by twurm** [comment] 2019-02-20 12:40
I think that’s just a typo I’ll give it another shot just to be sure.  Thanks for looking into this!

**Comment by r-win** [comment] 2019-05-06 13:28
Closing this issue for now. Please re-open if the issue persists.

**Closed as completed by r-win** 2019-05-06 13:28 UTC

**Comment by Compl1cation** [comment] 2019-11-08 13:30
I'm having a similar issue. Here is the problem.
I have two dashboards set up in two different projects that use a single Hangfire database.

I schedule the jobs from each project's schedulers by using queues and everything is fine.
When i started using Hangfire.Tags in project A it works fine on it's own, but when i run project B at the same time and open the dashboard from it's window then the jobs scheduling starts to fail for project A.

I've found out it's Hangfire.Tags because when i remove this package i have no issues running both of the apps at the same time.
